#User Scan Statistics and Settings
#Fri Apr 17 18:05:18 IST 2026
darkTheme=true
hashAlgorithm=SHA-256
lastFolder=/home/tahaur/Desktop/dummy folder for scan
minSizeKB=0
safeMode=false
skipHidden=true
totalGroups=198
totalSaved=1605996728
totalScanned=378
