#User Scan Statistics and Settings
#Fri Apr 17 15:33:55 IST 2026
darkTheme=false
hashAlgorithm=SHA-256
lastFolder=/home/tahaur/Desktop/dummy folder for scan
minSizeKB=0
safeMode=true
skipHidden=true
totalGroups=143
totalSaved=812653739
totalScanned=297
