#User Scan Statistics and Settings
#Thu Apr 23 16:20:56 IST 2026
darkTheme=false
hashAlgorithm=MD5
lastFolder=/home/tahaur/Desktop/dummy folder for scan
soundEnabled=true
soundVolume=1.0
totalGroups=140
totalSaved=1116112989
totalScanned=253
